name: secbox

services:
  secbox:
    build:
      context: ./toolbox
    image: secbox:local
    container_name: secbox
    init: true
    stdin_open: true
    tty: true
    user: "1000:1000"
    working_dir: /work
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
    security_opt:
      - no-new-privileges:true
    pids_limit: 512
    mem_limit: 4g
    cpus: 2.0
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=512m,mode=1777
      - /home/secbox:rw,nosuid,nodev,size=256m,uid=1000,gid=1000,mode=0700
    volumes:
      - ./work:/work:rw
      - ./labs:/labs:ro
      - ./scripts:/scripts:ro
      - ./wordlists:/wordlists:ro
    networks:
      - secbox-net
    restart: "no"

networks:
  secbox-net:
    driver: bridge
    internal: false
