services:

  secbox:
    build: ./toolbox

    container_name: secbox

    stdin_open: true
    tty: true

    working_dir: /work

    volumes:
      - ./work:/work
      - ./labs:/labs
      - ./scripts:/scripts
      - ./wordlists:/wordlists

    cap_drop:
      - ALL

    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

    security_opt:
      - no-new-privileges:true

    tmpfs:
      - /tmp